apiVersion: v1
name: nginx
version: 2.2.1
appVersion: 1.14.2
description: Chart for the nginx server
keywords:
- nginx
- http
- web
- www
- reverse proxy
home: http://www.nginx.org
icon: https://bitnami.com/assets/stacks/nginx/img/nginx-stack-220x234.png
sources:
- https://github.com/bitnami/bitnami-docker-nginx
maintainers:
- name: Bitnami
  email: containers@bitnami.com
engine: gotpl
