name: nginx
version: 2.1.0
appVersion: 1.14.2
description: Chart for the nginx server
keywords:
- nginx
- http
- web
- www
- reverse proxy
home: http://www.nginx.org
sources:
- https://github.com/bitnami/bitnami-docker-nginx
maintainers:
- name: Bitnami
  email: containers@bitnami.com
engine: gotpl
